allowBuilds:
  core-js: false
allowedDeprecatedVersions:
  get-graphql-from-jsonschema: '8.1.0'
  defekt: '9.3.0'
minimumReleaseAgeExclude:
  - '@interop/verifier-core@3.1.0'
  - '@interop/was-client@0.2.0'
